### ISSUE TITLE
Author order of publications

### ISSUE THREAD

**Issue by matthiasch** [InsightSoftwareConsortium/InsightJournal#115]
Hello,

I noticed that there is an issue with the order in which the authors appear. It's in alphabetical order (last name), not as on the paper or in the metadata. The author order is correct when browsing an issue.
Example:
- order correct: https://www.midasjournal.org/browse/issue/383
- order is alphabetical by last name: https://www.midasjournal.org/browse/publication/938

All publications in the above issue seem to be affected.

Thank you,
Matthias

**Comment by phcerdan** [comment]
Thanks again @matthiasch. 
We store `author_place` in `metadata.json`, but it is indeed ignored when rendered [here](https://github.com/InsightSoftwareConsortium/InsightJournal/blob/a302fe81234c1f2b797284a473d05c93d94a5475/src/templates/publication.js#L461-L470)
