### ISSUE TITLE
Unable to load a submission

### ISSUE THREAD

**Issue by ebrahimebrahim** [InsightSoftwareConsortium/InsightJournal#117]
The PDF seems to load forever for [this submission](https://www.insight-journal.org/browse/publication/176), even though [the data exists](https://data.kitware.com/#collection/5cb75e388d777f072b41e8db/folder/5cca0a768d777f072b80aaaf).

BTW I am delighted to see Insight Journal making a comeback as a modern website! :smiling_face_with_tear:

**Comment by thewtex** [comment]
@ebrahimebrahim thanks for the note! Corrected in https://github.com/InsightSoftwareConsortium/InsightJournal/pull/118

Contributions to IJ are certainly welcome!
