### ISSUE TITLE
Bring Back the Veggie MRIs

### ISSUE THREAD

**Issue by allisonbertrandsa** [InsightSoftwareConsortium/InsightJournal#129]
Please bring back the Veggie MRIs - they were the best!!!

Old link: http://www.insight-journal.org/midas/collection/view/194

**Comment by thewtex** [comment]
These were on a different journal than the IJ.

@jcfr has been looking at reconstituting this other server, if possible.

For the Veggie MRIs, you can find them here:

https://data.kitware.com/#user/568d8b868d777f429eac908f/folder/5b91a3388d777f43cc9e561c

**Comment by allisonbertrandsa** [comment]
You are the best - thanks!
