### ISSUE TITLE
Articles are not available

### ISSUE THREAD

**Issue by hjmjohnson** [InsightSoftwareConsortium/InsightJournal#163]
The article is not available:   https://www.insight-journal.org/browse/publication/65

Could the old website be made available until the new website is working.  Or is there a cache of the pdfs somewhere?

Could you add an estimated timeline for when the new site will be available?

Thanks,
Hans

**Comment by thewtex** [comment]
Hi Hans, the website is available but the provider for DNS/CDN is undergoing major changes and it appears they broke something :-(.

In the meantime, you can still file the website / article page here:
  https://bafybeiechwh4nxnfnp5zqsnbwqjbqhyeipbpt4ea4srcfjq4ywfptnyoiu.ipfs.dweb.link/browse/publication/65

and the PDFs are available here:

https://itk.mypinata.cloud/ipfs/bafybeialgmdqikskc56dhy2xrnio2te23xdzqdm77wtqxpxybr3ys5cpli/

**Comment by thewtex** [comment]
> Hi Hans, the website is available but the provider for DNS/CDN is undergoing major changes and it appears they broke something :-(.

The site is back up :-)

However, the PDF for publication 65 is not rendered, as you mentioned, Hans. Addressed here:

https://github.com/InsightSoftwareConsortium/InsightJournal/pull/164
