### ISSUE TITLE
Data: publication licenses

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/InsightJournal#28]
@phcerdan is it possible to add the publication licenses to metadata.json (in the legacy journal, viewable with the *View license* link.?

**Comment by phcerdan** [comment]
Sure, it seems the license is associated to the issues/collections in the legacy journal.

Options to where to put the license:
- Per publication
- Per journal
- Per Issue/Collection

I guess a license per publication suits best. Incoming.
