### ISSUE TITLE
Preserve RIRE data, submission results

### ISSUE THREAD

**Issue by thewtex** [InsightSoftwareConsortium/InsightJournal#56]
Currently provided at:

https://www.insight-journal.org/rire/index.php

We need folks to still able to access the provided articles, data, submission results.

@josephsnyder can you please run ScraPy on these pages? We will then host them and provide a redirect to the hosting location from the current location.

CC @aylward

**Comment by josephsnyder** [comment]
First pass can be found here:  https://gitlab.kitware.com/joe-snyder/tech-journal-mirror/-/commits/RIRE_saving

Saves much of the data to a flat directory, first output found here: https://drive.google.com/file/d/1Cy-0oyY0wGp54lsMyowqC8Fiu995_jZl/view?usp=sharing

Todo:

- [ ]  Save images on certain pages
- [ ]  Save "Results" downloads (HTTP 500 response for viewing any result object at the moment: https://www.insight-journal.org/rire/view_result.php?methodid=171077)
- [ ] Output directory structure?

**Comment by thewtex** [comment]
@josephsnyder awesome!!

Can the output be generated such that we can host it at another domain, i.e. `<domain>/index.php` vs `insight-journal.org/rire/index.php`?

**Comment by thewtex** [comment]
Additional updates added:

  https://github.com/InsightSoftwareConsortium/RIREWebsite

**Comment by thewtex** [comment]
We could not feasibly preserve submission results, but the data and description are now sustainable archived at

https://rire.insight-journal.org/

A redirect was created at

https://insight-journal.org/rire/index.php

for the old entry point.

Website sources:

https://github.com/InsightSoftwareConsortium/RIREWebsite
