### ISSUE TITLE
ISSN for the journals. Midas missing

### ISSUE THREAD

**Issue by phcerdan** [InsightSoftwareConsortium/InsightJournal#66]
Insight Journal: 2327-770X
VTK Journal: 2328-3459
Midas Journal:  None

I think we need a ISSN for crossref registration, but not 100% sure if it is required.

Who is managing the ISSN account for the Insight Journal right now?
It would be interesting to check that ISSN account. https://portal.issn.org/faq8

@thewtex

**Comment by thewtex** [comment]
@phcerdan I'll look into the ISSN registration.

**Comment by thewtex** [comment]
IJ: https://portal.issn.org/resource/ISSN/2327-770X
VTK Journal: https://portal.issn.org/resource/ISSN/2328-3459

**Comment by phcerdan** [comment]
An ISSN is required for crossref submission, we cannot upload the Midas publications without it, getting this error:
```xml
<?xml version="1.0" encoding="UTF-8"?>
<doi_batch_diagnostic status="completed" sp="a-cs1">
   <submission_id>1432751427</submission_id>
   <batch_id>20220103201109431620848965</batch_id>
   <record_diagnostic status="Failure" msg_id="28">
      <doi />
      <msg>Deposit contains title error: title: The MIDAS Journal must deposit with an ISSN and/or journal title DOI</msg>
   </record_diagnostic>
   <batch_data>
      <record_count>1</record_count>
      <success_count>0</success_count>
      <warning_count>0</warning_count>
      <failure_count>1</failure_count>
   </batch_data>
</doi_batch_diagnostic>
```
Two options I guess:
a) Get an ISSN for Midas Journal
b) Merge it into VTK or ITK journal?

**Comment by phcerdan** [comment]
Other option is to get a "journal title DOI" from crossref: https://www.crossref.org/documentation/content-registration/descriptive-metadata/journal-title-management/

I am exploring this.

**Comment by phcerdan** [comment]
Added a journal title doi for The Midas Journal:
![image](https://user-images.githubusercontent.com/3021667/147986947-7b2999be-8612-493e-b740-515d6bec937f.png)

doi: 10.54294/MIDAS

**Comment by phcerdan** [comment]
Registered dois for all journals:

```python
ij_journals_doi = {
    3:  "10.54294/Insight", # insight
    31: "10.54294/MIDAS", # midas
    35: "10.54294/VTK" # vtk
}

```
