### ISSUE TITLE
IPFS layout question

### ISSUE THREAD

**Issue by phcerdan** [InsightSoftwareConsortium/InsightJournal#69]
Hi @thewtex, 

https://github.com/InsightSoftwareConsortium/InsightJournal/blob/933d4c096d67347cac164821edf1cb421f632b62/src/templates/publication.js#L256-L265

A question about ipfs, from the code above, that "path" of `/articles/${pub_id}`, from where is it coming?
It's because you uploaded the files with that structure?
Is there a way I can explore the ipfs layout? Just out of curiosity. Thanks!

I have to download the latest revision data, to parse the citations of each article, and not sure if doing it via ipfs, or https://data.kitware.com/#collection/5cb75e388d777f072b41e8db

**Comment by thewtex** [comment]
@phcerdan this is the IPFS [Mutable File System (MFS)](https://docs.ipfs.io/concepts/file-systems/), which is a virtual filesystem. We mount IPFS nodes, similar to, e.g., mounting a hard drive to the root filesystem on Linux. IPFS has UnixFS nodes, which represent files and directories. 

You can browse any IPFS CID with an IPFS gateway, e.g.

https://gateway.pinata.cloud/ipfs/bafybeigk2vh72ukdc5d4j7q5xqujyk7em243h6ti2l22jrsvqae5mclp44

or with a tool like [ipfs-desktop](https://github.com/ipfs/ipfs-desktop).

You can use the MFS on your filesystem with the go-ipfs command line tool via `ipfs files [...]`.

You can get an IPFS node by CID, e.g.

```
ipfs get bafybeigk2vh72ukdc5d4j7q5xqujyk7em243h6ti2l22jrsvqae5mclp44
```

The current root nodes for are:

- ij-source-code: bafybeihuwin7g4yeioxvxcfjbmvxgujuhgp3p2esfjwih4zou3tkyblyzu
- ij-articles: bafybeibrvyapucsh5qlasikrmxc76tfwtjf3oyguvqziw2f6upg3hzj354
